version: "2"

services:
  hercules-base:
    image: projectignis/hercules-base
    build: .
    environment:
      - HERCULES_BASE_PORT=${HERCULES_BASE_PORT}
      - HERCULES_BASE_DB=${HERCULES_BASE_DB}
      - HERCULES_BASE_SECRET=${HERCULES_BASE_SECRET}
    expose:
      - ${HERCULES_BASE_PORT}
    ports:
      - "${HERCULES_BASE_HOST}:${HERCULES_BASE_PORT}"
    volumes:
      - ./${HERCULES_BASE_DB}:/hercules-base/${HERCULES_BASE_DB}

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_HOST}:9000"
    volumes:
      - ./minio:/minio
    command: server /minio
